[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

[[redirects]]
  from = "/download"
  to = "/#instalacion"
  status = 301

[[redirects]]
  from = "/apk"
  to = "https://ejemplo.com/descargas/gestor-creditos.apk"
  status = 302
